### ISSUE TITLE
about encoding

### ISSUE THREAD

**Issue by seobyeongky** [notatestuser/gift#51]
Hi, I am using gift on my server.
It is a nice package and everything good.
But there is one problem.
I put commit messages with Korean.
Commit messages are malformed.
I can't read it!
I found gift uses child_process.exec with binary encoding.
I tested with utf-8 encoding, and it works fine for just commit messages.
I think there is a reason for binary encoding, So I don't know how to fix this issue.
Any suggestion?

**Comment by notatestuser** [comment]
According to the commit where this was introduced (5af25bcf17912286df985726e07cac4ee1f0c6e8) binary encoding is used to retrieve the content of binary files. The encoding scheme could be configurable as an option to work around to this problem.

**Comment by seobyeongky** [comment]
OK. Thank you.
