### ISSUE TITLE
git ls-files --others --exclude-standard

### ISSUE THREAD

**Issue by RassaLibre** [notatestuser/gift#53]
Hello,
is it possible to execute the command bellow with Gift? I can not really find if so and how. 

`git ls-files --others --exclude-standard`

or

`git diff --name-only`

I need to execute this command and then loop over all the files and add them to the commit.
Thanks!

**Comment by notatestuser** [comment]
Something like this should do the trick:
```js
var options = {}, args = ["--others", "--exclude-standard"];
repo.git("ls-files", options, args, function(err, stdout, stderr) {
    // do something with results…
}
```

**Comment by RassaLibre** [comment]
Yes! You mister, you know! Thank you very much!
