### ISSUE TITLE
If path to repo contains whitespace - .exec is not working properly. 

### ISSUE THREAD

**Issue by andreyselitsky** [notatestuser/gift#58]
On Windows I'm facing issue that if my repo is located under path that has whitespaces I can't do simple .clone and .checkout (probably all other too) commands. 

Getting:

```
'git checkout  app/master.brandA'
'"C:\\Users\\DELL\\WebstormProjects\\tmp folder\\"',

Error: spawn ENOENT
  at errnoException (child_process.js:1001:11)
  at Process.ChildProcess._handle.onexit (child_process.js:792:34)

```

I think solution is to wrap path with ```'\"' + path + '\"'```

**Comment by notatestuser** [comment]
Okay, pull requests accepted!

**Comment by andreyselitsky** [comment]
@notatestuser I can create PR. but how to escape " in cofeescript?
I'm talking about this line:
```
  bash = "git clone #{repository} #{path}"
```

**Comment by notatestuser** [comment]
Something like this should do it:
```coffee
bash = "git clone \"#{repository}\" \"#{path}\""
```

**Comment by clinuz** [comment]
So, you noted the fix directly (which does work as I found the source of error and tested before looking here) but didn't submit the fix? You'd rather me (or someone else) fork the project and make the same change you typed out and submit a PR just to wait on you to merge...even though you could have fixed it right then? ...

Well, for anyone else who finds this, yes simply wrapping the output in double-quotes works as it is passed through to the CLI interpreter. You can do this on your end prior to passing the value into the function to avoid submitting a PR here and crossing your fingers that it would ever be accepted (e.g. `'\"' + PATH + '\"'`).

**Comment by notatestuser** [comment]
I don't use Windows and can't test this. There should also be a more sustainable way to do it with a little thought (by wrapping `exec` for instance). I'll apply the above fix for now.
