### ISSUE TITLE
Get currently checked out branch?

### ISSUE THREAD

**Issue by Efreak** [notatestuser/gift#67]
Please add a way to get the currently checked out branch.

The easiest way would likely be the following command, as _all_ it returns is the current branch.

```
git rev-parse --symbolic-full-name --abbrev-ref HEAD
```

Currently I have to do it by the following, which is hardly ideal for such a simple process...

``` javascript
var gift = require('gift')('.');
gift.status({"branch":true},function(err,rsp){
    for (var file in rsp.files) {
        if(file.indexOf('...') > -1) {
            console.log(file.substr(0,file.indexOf('...')));
        }
    }
});
```

Also, I don't see the {option:true} option formatting documented anywhere. I had to look at the source to figure out how to specify options...

**Comment by notatestuser** [comment]
Good shout. Would you mind sending a PR?

**Comment by gtanner** [comment]
Seems like that is what https://github.com/notatestuser/gift/blob/master/src/repo.coffee#L350-L364 should be doing.

without the optional name param:

```
git('.').branch(function (err, head) {
    // head object should contain the current branch
});
```
