### ISSUE TITLE
Clone a single branch

### ISSUE THREAD

**Issue by obxhdx** [notatestuser/gift#73]
Is it possible to perform a clone like the following:
`git clone http://domain/user/repo --branch gh-pages --single-branch gh-pages`.

I have an orphan branch that is part of a larger repo, and doing a full clone takes time. Therefore I'm looking for a faster approach, given that this is something that I'll do repeatedly in my CI environment.

**Comment by sparkleholic** [comment]
No answers for this ?
I'm looking for the same.

**Comment by sparkleholic** [comment]
I made a PR for this
https://github.com/notatestuser/gift/pull/91

**Comment by notatestuser** [comment]
Merged. Thank you.
