### ISSUE TITLE
git describe Support

### ISSUE THREAD

**Issue by cjbarth** [notatestuser/gift#87]
There doesn't seem to be any support for the `git describe` command. Am I missing that, or can it be added?

[https://git-scm.com/docs/git-describe](https://git-scm.com/docs/git-describe)

**Comment by notatestuser** [comment]
It can be added. Pull requests are welcome.

**Comment by cjbarth** [comment]
Thanks for merging this request. When is the next version due out (I guess 0.9.0) so that I can start (officially) using this?

**Comment by notatestuser** [comment]
I'll get it published today!

Get Outlook for iOS




On Tue, Jul 5, 2016 at 11:23 PM +0800, "cjbarth" <notifications@github.com> wrote:












Thanks for merging this request. When is the next version due out (I guess 0.9.0) so that I can start (officially) using this?

**Comment by notatestuser** [comment]
Published in v0.9.0.
