### ISSUE TITLE
Is there a way to tell which credentials are being used?

### ISSUE THREAD

**Issue by zaeni** [notatestuser/gift#89]
I'm running into an issue trying to git clone from a gitlab repository. Running the js script locally produces the right results, but running it on a build server results in an error of 'No user or key was provided.'

Is there a way to print the credentials being used by gift at the time of the operation? Or is there a way to set it before a git clone?

**Comment by notatestuser** [comment]
Try checking the output of `$ git config credential.helper`

Gift should be using the same CLI binary. If you'd really like to see it in node:
`node -e "require('gift')().config((err, conf) => console.log(conf.items['credential.helper']))`

The solution can differ between platforms but if you're dealing with Windows you might want to check out [Microsoft's Git Credential Manager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows). On Linux I tend to have luck with cloning on CLI first to address the first password prompt.

**Comment by zaeni** [comment]
Thanks! that command definitely helped!
